# Name of your application. Used to uniquely configure containers.
service: quran-frontend

# Name of the container image.
image: ghcr.io/quran/quran-frontend
# image: quran/quran-frontend

# Deploy to these servers.
servers: [157.180.34.63, 135.181.32.139]

ssh:
  config: true
  user: root

# Credentials for your image host.
registry:
  server: ghcr.io
  username: quran
  password:
    - KAMAL_GH_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: arm64
  # context: frontend
  driver: docker
  secrets:
  - QURAN_FRONTEND_ENV_CONTENT

boot:
  limit: 1 # Can also specify as a percentage of total hosts, such as "25%"
  wait: 60

proxy:
  host: onprem-test.quran.com
  ssl: false
  app_port: 80
  healthcheck:
    interval: 3
    path: /
    timeout: 60
