# Name of your application. Used to uniquely configure containers.
service: quran-frontend

# Name of the container image.
image: ghcr.io/quran/quran-frontend

# Deploy to these servers.
servers:
  web:
    - 10.1.0.3
    - 10.1.0.2

# ssh:
#   user: root
#   keys_only: true
#   keys: [ "~/.ssh/id_ed25519" ]

# Credentials for your image host.
registry:
  server: ghcr.io
  username: quran

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_GH_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: arm64
  context: ./quran-frontend-next
  driver: docker
  secrets:
  - QURAN_FRONTEND_ENV_CONTENT

boot:
  limit: 1 # Can also specify as a percentage of total hosts, such as "25%"
  wait: 60

proxy:
  host: onprem-test.quran.com
  ssl: false
  app_port: 80
  healthcheck:
    interval: 3
    path: /
    timeout: 60
