service: quran-frontend
image: ghcr.io/quran/quran-frontend

servers: [157.180.34.63, 135.181.32.139]

ssh:
  config: true
  user: root

registry:
  server: ghcr.io
  username: quran
  password:
    - GITHUB_TOKEN

builder:
  arch: arm64
  context: /home/web/actions-runner/_work/deployments/deployments/
  driver: docker
  cache:
    type: gha
    options: mode=max
    image: kamal-app-build-cache

boot:
  limit: 1 # Can also specify as a percentage of total hosts, such as "25%"
  wait: 60

proxy:
  host: onprem-test.quran.com
  ssl: false
  app_port: 80
  healthcheck:
    interval: 3
    path: /
    timeout: 60

env:
  secret:
    - GITHUB_TOKEN
