name: Deploy with Kamal

on:
  # Automatic runs when code is pushed
  push:
    branches:
      - testing
      - staging
      - production

  # Manual runs from the GitHub UI
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: false
        default: production          # UI default
        type: choice
        options: [testing, staging, production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Map each branch to the matching Kamal environment name
    strategy:
      matrix:
        include:
          - branch: refs/heads/testing     # <‑‑ git ref
            env:    testing               # <‑‑ KAMAL_ENV + GitHub Environment
          - branch: refs/heads/staging
            env:    staging
          - branch: refs/heads/production
            env:    production

    # Only run the matrix row that matches the event
    if: >-
      (github.event_name == 'push' &&
       github.ref == matrix.branch) ||
      (github.event_name == 'workflow_dispatch' &&
       (inputs.environment == '' || inputs.environment == matrix.env))

    # Prevent parallel deployments to the same target
    concurrency:
      group: deploy-${{ matrix.env }}
      cancel-in-progress: true

    # Tells GitHub which “Environment” (Secrets/Protection rules) to use
    environment: ${{ matrix.env }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'      # pin Ruby, caches gems automatically

      - name: Install Kamal
        run: gem install kamal -v 1.7.3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: docker/setup-buildx-action@v3

      - name: Deploy with Kamal
        run: |
          KAMAL_ENV=${{ matrix.env }} kamal deploy
