name: Kamal deploy

on:
  workflow_dispatch:

jobs:
  kamal-deploy:
    name: Kamal deploy
    runs-on: ubuntu-latest
    env:
    concurrency:
      group: default_environment
      cancel-in-progress: true
    environment:
      name: default
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install Kamal
        run: |
          gem install kamal -v 1.7.3
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: kamal deploy
        run: kamal deploy
