name: Kamal Deploy

on:
  push:
    branches: [testing, staging, pre-live, production]
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        required: true
        default: testing
        type: choice
        options: [testing, staging, pre-live, production]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: self-hosted

    concurrency:
      group: deploy-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    environment: ${{ github.head_ref || github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout quran.com-frontend-next
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: quran/quran.com-frontend-next
          ref: ${{ github.head_ref || github.ref_name }}
          path: frontend
          sparse-checkout-cone-mode: false   # turn off cone so we can use "!" negation
          sparse-checkout: |
            /*
            !/public/fonts/

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'      # pin Ruby, caches gems automatically
          bundler-cache: true

      - run: gem install kamal -v 2.5.3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: docker/setup-buildx-action@v3

      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Deploy
        env:
          QURAN_FRONTEND_ENV_CONTENT: ${{ secrets.QURAN_FRONTEND_ENV_CONTENT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVER_IPS: ${{ secrets.SERVER_IPS }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
        run: |
          echo "$QURAN_FRONTEND_ENV_CONTENT" > ./frontend/.env
          perl -pe 's/\$SERVER_IPS\$/$ENV{SERVER_IPS}/ge;
                    s/\$HOSTNAME\$/$ENV{HOSTNAME}/ge;
                    s/\$PWD\$/$ENV{PWD}/ge' -i kamal.yml
          perl -0777 -i -pe 's/"postinstall": "husky",\n//g' ./frontend/package.json
          kamal lock release -c kamal.yml  # in case a job was cancelled
          kamal deploy -q -c kamal.yml
